// Code generated by "stringer -type=ErrCode"; DO NOT EDIT.

package errors

import "strconv"

const _ErrCode_name = "AssertionErrorParseErrorServerNotAvailableNetworkErrorConnectionResetErrorAdbErrorDeviceNotFoundFileNoExistErrorRemoteStartFailed"

var _ErrCode_index = [...]uint8{0, 14, 24, 42, 54, 74, 82, 96, 112, 129}

func (i ErrCode) String() string {
	if i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
